version: "3"

tasks:
  get-aws-creds:
    cmds:
      - echo "Task - testing provider"
      - go clean -modcache
      - go test ./test/provider_test.go
  debug:
    cmds:
      - echo "Task - testing provider with visible browser and added logging"
      - go clean -modcache
      - go test ./test/provider_test.go -v -rod="show,slow=1s,trace"
  run-cli:
    cmds:
      - echo "Task - running interactive CLI"
      - go clean -testcache
      - go run ./scripts/cli.go 
  cli-debug:
    cmds:
      - echo "Task - running interactive CLI"
      - go clean -testcache
      - go run ./scripts/cli.go -v -rod="show,slow=1s,trace"
  test-all:
    cmds:
      - echo "Task - testing all methods"
      - go clean -modcache
      - cd /test
      - go test -v
  